version: "3.9"

services:
  api:
    build: .
    container_name: enova-academy
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=mydb;user=root;password=root
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend

  db:
    image: mysql:8.0.38
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  backend:
    driver: bridge
